BloodBankManagement/Controllers/ListDonorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BloodBankManagement.Data;
using BloodBankManagement.Models;
using BloodBankManagement.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BloodBankManagement.Controllers
{
    [Authorize]
    public class ListDonorController : Controller
    {
        private readonly BloodBankDbContext context;

        public ListDonorController(BloodBankDbContext dbContext)
        {
            context = dbContext;
        }
        public IActionResult Index()
        {
            List<Donor> donors = context.Donors.Include(d => d.Address).ToList();
            ViewBag.donors = donors;
            //Add the locations into ViewBag to be used as Markers in google map.
            List<string> locations = new List<string>();
            foreach(Donor d in donors)
            {
                locations.Add(d.Address.City + "," + d.Address.State);
            }
            ViewBag.locations = locations;
            return View(donors);
        }
        public IActionResult EditDonor(string value)
        {
            Donor editDonor = context.Donors.Find(int.Parse(value));
            Address donorAddress = context.Address.Find(editDonor.AddressId);
            editDonor.Address = donorAddress;
            AddDonorViewModel donorViewModel = new AddDonorViewModel(editDonor);
            return View(donorViewModel);
        }
        [HttpPost]
        public IActionResult EditDonor(AddDonorViewModel donorViewModel)
        {
            if (ModelState.IsValid)
            {
                Donor donorToEdit = context.Donors.Find(donorViewModel.Id);
                Address addressToEdit = context.Address.Find(donorToEdit.AddressId);

                donorToEdit.FirstName = donorViewModel.FirstName;
                donorToEdit.LastName = donorViewModel.LastName;
                donorToEdit.DateOfBirth = donorViewModel.DateOfBirth;
                donorToEdit.Email = donorViewModel.Email;
                donorToEdit.ContactNum = donorViewModel.ContactNum;
                donorToEdit.BloodGroup = donorViewModel.BloodGroup;

                addressToEdit.Line1 = donorViewModel.Line1;
                addressToEdit.Line2 = donorViewModel.Line2;
                addressToEdit.City = donorViewModel.City;
                addressToEdit.State = donorViewModel.State;
                addressToEdit.Zip = donorViewModel.Zip;

                context.Donors.Update(donorToEdit);
                context.Address.Update(addressToEdit);
                context.SaveChanges();
                TempData["msg"] = "Donor Id: "+donorToEdit.Id+" updated successfully.";
                return Redirect("/StaffLogin");
            }

            return View(donorViewModel);
        }
    }
}

BloodBankManagement/Controllers/ManageStockController.cs
using BloodBankManagement.Data;
using BloodBankManagement.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BloodBankManagement.Controllers
{
    public class ManageStockController:Controller
    {
        private readonly BloodBankDbContext context;

        public ManageStockController(BloodBankDbContext dbContext)
        {
            context = dbContext;
        }
        public IActionResult Index()
        {
            ViewBag.bloodStock = context.BloodStock.ToList();
            return View();
        }
        public IActionResult EditStock(string value)
        {
            BloodStock bloodStock = context.BloodStock.Find(int.Parse(value));
            ManageStockViewModel manageStockViewModel = new ManageStockViewModel(bloodStock);
            return View(manageStockViewModel);
        }
        [HttpPost]
        public IActionResult EditStock(ManageStockViewModel manageStockViewModel, string radioButton, string amountToUpdate)
        {
            if (ModelState.IsValid)
            {
                BloodStock bloodStockToUpdate = context.BloodStock.Find(manageStockViewModel.Id);
               

                if(radioButton == "Increase")
                {
                    bloodStockToUpdate.Quantity = manageStockViewModel.Quantity + int.Parse(amountToUpdate);
                }
                else
                {
                    if(manageStockViewModel.Quantity < int.Parse(amountToUpdate))
                    {
                        ModelState.AddModelError("AmountToUpdate", "Please enter a quantity less than "+manageStockViewModel.Quantity +" units");
                        return View(manageStockViewModel);
                    }
                    bloodStockToUpdate.Quantity = manageStockViewModel.Quantity - int.Parse(amountToUpdate);
                }

                context.BloodStock.Update(bloodStockToUpdate);
                context.SaveChanges();
                TempData["msg"] = "Blood Group: " + bloodStockToUpdate.BloodGroup + " updated to "+ bloodStockToUpdate.Quantity+" units.";
                return Redirect("/ManageStock");
            }
            return View(manageStockViewModel);
        }
    }
}

BloodBankManagement/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BloodBankManagement.Data;
using BloodBankManagement.Models;
using BloodBankManagement.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BloodBankManagement.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        private readonly BloodBankDbContext context;

        public SearchController(BloodBankDbContext dbContext)
        {
            context = dbContext;
        }
        public IActionResult Index()
        {
            ViewBag.checkedValue = "BloodGroup";
            return View();
        }
        public IActionResult Results(string searchType, string searchTerm)
        {
            List<Donor> donors;
            List<SearchDonorViewModel> displayDonors = new List<SearchDonorViewModel>();

            if (string.IsNullOrEmpty(searchTerm))
            {
                donors = context.Donors.Include(a => a.Address).ToList();
                   
                foreach (var donor in donors)
                {
                 SearchDonorViewModel result = new SearchDonorViewModel(donor);
                    displayDonors.Add(result);
                }
            }
            else
            {
                if (searchType == "BloodGroup")
                {
                    donors = context.Donors
                        .Where(d => d.BloodGroup == searchTerm.ToUpper()).Include(a => a.Address)
                        .ToList();

                    foreach (Donor donor in donors)
                    {
                        SearchDonorViewModel result = new SearchDonorViewModel(donor);
                        displayDonors.Add(result);
                    }

                }
                if (searchType == "Location")
                {                  
                    donors = context.Donors
                        .Include(a => a.Address)
                        .Where(a => a.Address.City.ToLower() == searchTerm.ToLower()
                        || a.Address.State.ToLower() == searchTerm.ToLower())
                        .ToList();
                    foreach (Donor donor in donors)
                    {
                        SearchDonorViewModel result = new SearchDonorViewModel(donor);
                        displayDonors.Add(result);
                    }
                }
            }

            ViewBag.donors = displayDonors;
            ViewBag.checkedValue = searchType;
            return View("Index");
        }
    }
}

BloodBankManagement/Controllers/StaffLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BloodBankManagement.Data;
using BloodBankManagement.Models;
using BloodBankManagement.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BloodBankManagement.Controllers
{
    public class StaffLoginController : Controller
    {
        private readonly BloodBankDbContext context;

        public StaffLoginController(BloodBankDbContext dbContext)
        {
            context = dbContext;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddDonor()
        {
           AddDonorViewModel addDonorViewModel = new AddDonorViewModel();
            ViewBag.fromPage = "Add";
            return View(addDonorViewModel);
        }

        [HttpPost]
        public IActionResult AddDonor(AddDonorViewModel addDonorViewModel)
        {
            if (ModelState.IsValid)
            {
                Address address = new Address(addDonorViewModel.Line1, addDonorViewModel.Line2, addDonorViewModel.City,
                    addDonorViewModel.State, addDonorViewModel.Zip);

                Donor newDonor = new Donor
                {
                    FirstName = addDonorViewModel.FirstName,
                    LastName = addDonorViewModel.LastName,
                    DateOfBirth = addDonorViewModel.DateOfBirth,
                    Email = addDonorViewModel.Email,
                    Address = address,
                    ContactNum = addDonorViewModel.ContactNum,
                    BloodGroup = addDonorViewModel.BloodGroup
                };

                // EventData.Add(newEvent);
                context.Donors.Add(newDonor);
                context.SaveChanges();
                TempData["msg"] = "New Donor Added Successfully.";
                if (User.Identity.IsAuthenticated)
                {
                    return Redirect("/StaffLogin");
                }
                else
                {
                    TempData["msg"] = "Thank you for volunteering!";
                    return Redirect("/Home");
                }
                    
            }

            return View(addDonorViewModel);
        }

        [Authorize]
        public IActionResult DeleteDonor()
        {
            ViewBag.donors = context.Donors.Include(d => d.Address).ToList();
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult DeleteDonor(int[] donorIds)
        {
            foreach (int donorId in donorIds)
            {
                Donor theDonor = context.Donors.Find(donorId);
                Address donorAddress = context.Address.Find(theDonor.AddressId);
                context.Address.Remove(donorAddress);
                context.Donors.Remove(theDonor);
            }
            context.SaveChanges();
            TempData["msg"] = donorIds.Count()+ " Donor Deleted.";
            return Redirect("/StaffLogin");
        }
    }
}

BloodBankManagement/Views/StaffLogin/AddDonor.cshtml
@model BloodBankManagement.ViewModel.AddDonorViewModel;
    <div class="container">
        <div class="row">
            <div class="col-md-10 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <form asp-controller="StaffLogin" asp-action="AddDonor" method="post">
                            <div class="row">
                                <div class="col-md-12">

                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <h4>Add Donor</h4>
                                    }
                                    else
                                    {
                                        <h4>Please update the following details to donate blood</h4>
                                    }
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <hr />
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group required">
                                        <label asp-for="FirstName" class="font-weight-bold">First Name</label>
                                        <input asp-for="FirstName" placeholder="First Name" class="form-control" value="@Model.FirstName" />
                                        <span asp-validation-for="FirstName"></span>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group required">
                                        <label asp-for="LastName" class="font-weight-bold">Last Name</label>
                                        <input asp-for="LastName" placeholder="Last Name" class="form-control" />
                                        <span asp-validation-for="LastName"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group required">
                                        <label asp-for="DateOfBirth" class="font-weight-bold"></label>
                                        <input asp-for="DateOfBirth" class="form-control" />
                                        <span asp-validation-for="DateOfBirth"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group required">
                                        <label asp-for="BloodGroup" class="font-weight-bold">Blood Group</label>
                                        <select asp-for="BloodGroup" asp-items="Model.BloodGroups" class="form-control"></select>
                                        <span asp-validation-for="BloodGroup"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group required">
                                        <label asp-for="Email" class="font-weight-bold"></label>
                                        <input asp-for="Email" class="form-control" placeholder="Email address" />
                                        <span asp-validation-for="Email"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group required">
                                        <label asp-for="ContactNum" class="font-weight-bold"></label>
                                        <input asp-for="ContactNum" class="form-control" placeholder="Phone Number" />
                                        <span asp-validation-for="ContactNum"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group required">
                                        <label asp-for="Line1" class="font-weight-bold">Address Line 1</label>
                                        <input asp-for="Line1" class="form-control" />
                                        <span asp-validation-for="Line1"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="Line2" class="font-weight-bold">Address Line 2</label>
                                        <input asp-for="Line2" class="form-control" />
                                        <span asp-validation-for="Line2"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group required">
                                        <label asp-for="City" class="font-weight-bold"></label>
                                        <input asp-for="City" class="form-control" placeholder="City" />
                                        <span asp-validation-for="City"></span>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group required">
                                        <label asp-for="State" class="font-weight-bold"></label>
                                        <select asp-for="State" asp-items="Model.States" class="form-control"></select>
                                        <span asp-validation-for="State"></span>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group required">
                                        <label asp-for="Zip" class="font-weight-bold"></label>
                                        <input asp-for="Zip" class="form-control" placeholder="ZIP Code" />
                                        <span asp-validation-for="Zip"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <hr />
                                </div>
                            </div>
                            <div class="row">
                                    <div class="col-12 mx-auto">
                                        <div class="form-group">
                                            <input type="submit" value="Submit" class="btn-primary btn-block btn-lg" />
                                        </div>
                                    </div>
                            </div>                        
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

BloodBankManagement/Views/StaffLogin/DeleteDonor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container">
    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Edit Donor</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <hr />
                        </div>
                    </div>
                    @if (ViewBag.donors.Count == 0)
                    {
                        <div class="row">
                            <div class="col-md-12">
                                <h4>No Donor data available!</h4>
                            </div>
                        </div>
                    }
                    else
                    {

                        <form method="post">
                            <div class="row">
                                <div class="col-md-12 align-content-center">
                                    <table class="donor-listing">
                                        <tr>
                                            <th>Donor ID</th>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Location</th>
                                            <th>Blood Group</th>
                                            <th>Select the Donor</th>
                                        </tr>

                                        @foreach (var donor in ViewBag.donors)
                                        {
                                            <tr>
                                                <td>@donor.Id</td>
                                                <td>@donor.FirstName</td>
                                                <td>@donor.LastName</td>
                                                <td>@donor.Address.City, @donor.Address.State</td>
                                                <td>@donor.BloodGroup</td>
                                                <td><input type="checkbox" name="donorIds" value="@donor.Id" class="form-control"/></td>
                                            </tr>
                                        }
                                    </table>
                                </div>
                            </div>
                            <hr />
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">                              
                                        <input type="submit" value="Delete Selected Donors" class="btn-danger btn-lg display-4"/>
                                    </div>
                                </div>
                            </div>
                        </form>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

BloodBankManagement/Views/StaffLogin/Index.cshtml
@*@model List<BloodBankManagement.Models.HomeController>*@
<div class="container">
    <div class="col-md-10 mx-auto">
        <div class="card">
            <div class="card-body">

                <div class="row">
                    <div class="col-md-12">
                        @if (TempData["msg"] != null)
                        {
                            <h4 class="alert-info">@TempData["msg"].ToString()</h4>
                        }
                    </div>
                </div>
                <div class="pb-3 row">
                    <div class="h4 col-md-12 text-center">
                        <a asp-controller="StaffLogin" asp-action="AddDonor" class="page-link">Add Donor</a>
                    </div>
                </div>
                <div class="pb-3 row">
                    <div class="h4 col-md-12 text-center">
                        <a asp-controller="StaffLogin" asp-action="DeleteDonor" class="page-link">Delete Donor</a>
                    </div>
                </div>
                <div class="pb-3 row">
                    <div class="h4 col-md-12 text-center">
                        <a asp-controller="Search" class="page-link">Search Donor</a>
                    </div>
                </div>
                <div class="pb-3 row">
                    <div class="h4 col-md-12 text-center">
                        <a asp-controller="ListDonor" class="page-link">Donor List</a>
                    </div>
                </div>
                <div class="pb-3 row">
                    <div class="h4 col-md-12 text-center">
                        <a asp-controller="ManageStock" class="page-link">Manage Stock</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BloodBankManagement/Views/StaffLogin/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h3>List Donors</h3>
@if (ViewBag.donors.Count == 0)
{
    <p>No Donor data available!</p>
}
else
{
    <form method="post">
        <table class="donor-listing">
            <tr>
                <th>Donor ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Location</th>
                <th>Blood Group</th>
            </tr>

            @foreach (var donor in ViewBag.donors)
            {
                <tr>
                    <td>@donor.Id</td>
                    <td>@donor.FirstName</td>
                    <td>@donor.LastName</td>
                    <td>@donor.Address.City, @donor.Address.State</td>
                    <td>@donor.BloodGroup</td>
                </tr>
            }
        </table>
    </form>
}